"""add rbac tables

Revision ID: fd90462691b5
Revises: eafc0d83cadb
Create Date: 2026-07-31 12:45:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd90462691b5'
down_revision: Union[str, Sequence[str], None] = 'eafc0d83cadb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Required as the referenced side of the composite FK from
    # user_role_assignments(user_id, tenant_id) -> users(id, tenant_id).
    op.create_unique_constraint(
        'uq_users_id_tenant_id', 'users', ['id', 'tenant_id']
    )

    op.create_table(
        'permissions',
        sa.Column('slug', sa.String(length=100), nullable=False),
        sa.Column('description', sa.String(length=255), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('slug', name='uq_permissions_slug'),
    )
    op.create_index(op.f('ix_permissions_slug'), 'permissions', ['slug'], unique=False)

    op.create_table(
        'roles',
        sa.Column('tenant_id', sa.UUID(), nullable=True),
        sa.Column('slug', sa.String(length=100), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('is_builtin', sa.Boolean(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "tenant_id IS NULL OR slug NOT IN ('tenant_admin', 'manager', 'employee', 'viewer')",
            name='ck_roles_reserved_slug',
        ),
        sa.CheckConstraint(
            "(tenant_id IS NULL AND is_builtin IS TRUE) OR "
            "(tenant_id IS NOT NULL AND is_builtin IS FALSE)",
            name='ck_roles_scope_matches_builtin',
        ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_roles_tenant_id_tenants'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_roles_tenant_id'), 'roles', ['tenant_id'], unique=False)
    op.create_index(
        'uq_roles_slug_builtin', 'roles', ['slug'],
        unique=True, postgresql_where=sa.text('tenant_id IS NULL'),
    )
    op.create_index(
        'uq_roles_tenant_id_slug_custom', 'roles', ['tenant_id', 'slug'],
        unique=True, postgresql_where=sa.text('tenant_id IS NOT NULL AND deleted_at IS NULL'),
    )

    op.create_table(
        'role_permissions',
        sa.Column('role_id', sa.UUID(), nullable=False),
        sa.Column('permission_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name='fk_role_permissions_permission_id_permissions'),
        sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='fk_role_permissions_role_id_roles'),
        sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    )
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)

    op.create_table(
        'user_role_assignments',
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('role_id', sa.UUID(), nullable=False),
        sa.Column('assigned_by_user_id', sa.UUID(), nullable=True),
        sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('revoked_by_user_id', sa.UUID(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id', 'tenant_id'], ['users.id', 'users.tenant_id'],
            name='fk_user_role_assignments_user_id_tenant_id_users',
        ),
        sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], name='fk_user_role_assignments_assigned_by_user_id_users'),
        sa.ForeignKeyConstraint(['revoked_by_user_id'], ['users.id'], name='fk_user_role_assignments_revoked_by_user_id_users'),
        sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='fk_user_role_assignments_role_id_roles'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_user_role_assignments_role_id'), 'user_role_assignments', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_role_assignments_assigned_by_user_id'), 'user_role_assignments', ['assigned_by_user_id'], unique=False)
    op.create_index(op.f('ix_user_role_assignments_revoked_by_user_id'), 'user_role_assignments', ['revoked_by_user_id'], unique=False)
    op.create_index(
        'uq_user_role_assignments_user_id_role_id_active',
        'user_role_assignments', ['user_id', 'role_id'],
        unique=True, postgresql_where=sa.text('revoked_at IS NULL'),
    )
    op.create_index(
        'ix_user_role_assignments_user_id_tenant_id_active',
        'user_role_assignments', ['user_id', 'tenant_id'],
        unique=False, postgresql_where=sa.text('revoked_at IS NULL'),
    )

    op.create_table(
        'system_role_assignments',
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('system_role', sa.String(length=50), nullable=False),
        sa.Column('assigned_by_user_id', sa.UUID(), nullable=True),
        sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('revoked_by_user_id', sa.UUID(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint("system_role IN ('super_admin')", name='ck_system_role_assignments_system_role'),
        sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], name='fk_system_role_assignments_assigned_by_user_id_users'),
        sa.ForeignKeyConstraint(['revoked_by_user_id'], ['users.id'], name='fk_system_role_assignments_revoked_by_user_id_users'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_system_role_assignments_user_id_users'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_system_role_assignments_user_id'), 'system_role_assignments', ['user_id'], unique=False)
    op.create_index(op.f('ix_system_role_assignments_assigned_by_user_id'), 'system_role_assignments', ['assigned_by_user_id'], unique=False)
    op.create_index(op.f('ix_system_role_assignments_revoked_by_user_id'), 'system_role_assignments', ['revoked_by_user_id'], unique=False)
    op.create_index(
        'uq_system_role_assignments_user_id_system_role_active',
        'system_role_assignments', ['user_id', 'system_role'],
        unique=True, postgresql_where=sa.text('revoked_at IS NULL'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_system_role_assignments_user_id_system_role_active', table_name='system_role_assignments')
    op.drop_index(op.f('ix_system_role_assignments_revoked_by_user_id'), table_name='system_role_assignments')
    op.drop_index(op.f('ix_system_role_assignments_assigned_by_user_id'), table_name='system_role_assignments')
    op.drop_index(op.f('ix_system_role_assignments_user_id'), table_name='system_role_assignments')
    op.drop_table('system_role_assignments')

    op.drop_index('ix_user_role_assignments_user_id_tenant_id_active', table_name='user_role_assignments')
    op.drop_index('uq_user_role_assignments_user_id_role_id_active', table_name='user_role_assignments')
    op.drop_index(op.f('ix_user_role_assignments_revoked_by_user_id'), table_name='user_role_assignments')
    op.drop_index(op.f('ix_user_role_assignments_assigned_by_user_id'), table_name='user_role_assignments')
    op.drop_index(op.f('ix_user_role_assignments_role_id'), table_name='user_role_assignments')
    op.drop_table('user_role_assignments')

    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_table('role_permissions')

    op.drop_index('uq_roles_tenant_id_slug_custom', table_name='roles')
    op.drop_index('uq_roles_slug_builtin', table_name='roles')
    op.drop_index(op.f('ix_roles_tenant_id'), table_name='roles')
    op.drop_table('roles')

    op.drop_index(op.f('ix_permissions_slug'), table_name='permissions')
    op.drop_table('permissions')

    op.drop_constraint('uq_users_id_tenant_id', 'users', type_='unique')
    # ### end Alembic commands ###
